# Generated by Django 2.2.16 on 2022-06-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220531_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
